Repository SDP-Rock-Paper-Scissors/RockPaperScissors, pull requests merged in 2022-05, with the labels that each got.

#99 Feat/gamemode multi game
  app/src/androidTest/java/ch/epfl/sweng/rps/StatisticsFragmentTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/services/FirebaseGameServiceTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/services/MatchmakingServiceTest.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Game.kt
  app/src/main/java/ch/epfl/sweng/rps/models/GameMode.kt
  app/src/main/java/ch/epfl/sweng/rps/services/MatchmakingService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/OfflineGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/MatchViewModel.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/settings/SettingsActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/Utils.kt
  app/src/test/java/ch/epfl/sweng/rps/models/GameModeTest.kt
  app/src/test/java/ch/epfl/sweng/rps/models/GameTest.kt
  app/src/test/java/ch/epfl/sweng/rps/services/OfflineGameServiceTest.kt
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/src/index.ts
  firebase/functions/src/test_framework.ts
  firebase/functions/src/tests.ts
Labels: Waiting for review

#104 Feat/tic tac toe UI
  app/src/androidTest/java/ch/epfl/sweng/rps/TestUtils.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/TicTacToeTest.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/HomeFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/tictactoe/TicTacToeChoiceFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/tictactoe/TicTacToeFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/tictactoe/TicTacToeViewModel.kt
  app/src/main/res/drawable-v24/count_background.png
  app/src/main/res/drawable-v24/cross.png
  app/src/main/res/drawable-v24/grid.png
  app/src/main/res/drawable-v24/nought.png
  app/src/main/res/drawable-v24/profile_img.png
  app/src/main/res/drawable/button_2.xml
  app/src/main/res/drawable/radio_button_checked.xml
  app/src/main/res/drawable/radio_button_unchecked.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_tictactoe.xml
  app/src/main/res/layout/fragment_tictactoe_choice.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: actual: 9h, Waiting for review

#100 Feat/firebase more games
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/rps/FirebaseTests.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/StatisticsFragmentTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/services/FirebaseGameServiceTest.kt
  app/src/main/java/ch/epfl/sweng/rps/db/FirebaseHelper.kt
  app/src/main/java/ch/epfl/sweng/rps/db/FirebaseRepository.kt
  app/src/main/java/ch/epfl/sweng/rps/db/LocalRepository.kt
  app/src/main/java/ch/epfl/sweng/rps/db/Repository.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Game.kt
  app/src/main/java/ch/epfl/sweng/rps/models/GameMode.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Hand.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Round.kt
  app/src/main/java/ch/epfl/sweng/rps/services/FirebaseGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/OfflineGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/settings/SettingsActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/tictactoe/TicTacToeChoiceFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/tictactoe/TicTacToeFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/Utils.kt
  app/src/test/java/ch/epfl/sweng/rps/models/GameModeTest.kt
  app/src/test/java/ch/epfl/sweng/rps/models/GameTest.kt
  app/src/test/java/ch/epfl/sweng/rps/models/HandTest.kt
  app/src/test/java/ch/epfl/sweng/rps/models/RoundTest.kt
  app/src/test/java/ch/epfl/sweng/rps/models/TicTacToe.kt
  firebase/functions/src/index.ts
Labels: Waiting for review

#98 Add an onboarding screen
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/rps/LoadingActivityTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/SettingsPageTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/TestUtils.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/ui/onboarding/OnBoardingActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/rps/LoadingActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/LoginActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/settings/SettingsActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/Utils.kt
  app/src/main/res/drawable/ic_baseline_dashboard_24.xml
  app/src/main/res/drawable/ic_baseline_delete_24.xml
  app/src/main/res/drawable/ic_baseline_navigate_next_24.xml
  app/src/main/res/drawable/ic_baseline_videogame_asset_24.xml
  app/src/main/res/font/montserrat.xml
  app/src/main/res/layout/activity_loading_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/on_boarding_activity.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/header_preferences.xml
Labels: Waiting for review

#111 fixed deprecated kotlin extentions
  app/build.gradle
  app/src/main/java/ch/epfl/sweng/rps/ui/leaderboard/LeaderBoardPlayerAdapter.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/leaderboard/LeaderboardFragment.kt
  app/src/main/res/layout/content_scrolling.xml
Labels: Waiting for review

#106 fix
  app/src/androidTest/java/ch/epfl/sweng/rps/GameButtonsTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/LeaderBoardFragmentTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/LoadingActivityTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/LoginPageTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/MainActivityTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/ProfileFragmentTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/SettingsPageTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/StatisticsFragmentTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/TestUtils.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/TicTacToeTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/ui/friends/FriendsFragmentTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/ui/onboarding/OnBoardingActivityTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/utils/LogServiceTest.kt
  app/src/main/java/ch/epfl/sweng/rps/LoadingActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/models/FriendRequest.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Game.kt
  app/src/main/java/ch/epfl/sweng/rps/models/GameMode.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/L.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/LogService.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/Utils.kt
  app/src/test/java/ch/epfl/sweng/rps/models/GameModeTest.kt
Labels: actual: 4h, Waiting for review

#118 Feat/leaderboard filter
  app/src/androidTest/java/ch/epfl/sweng/rps/CacheTests.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/LeaderBoardFragmentTest.kt
  app/src/main/java/ch/epfl/sweng/rps/db/FirebaseHelper.kt
  app/src/main/java/ch/epfl/sweng/rps/db/FirebaseRepository.kt
  app/src/main/java/ch/epfl/sweng/rps/db/LocalRepository.kt
  app/src/main/java/ch/epfl/sweng/rps/db/Repository.kt
  app/src/main/java/ch/epfl/sweng/rps/models/TotalScore.kt
  app/src/main/java/ch/epfl/sweng/rps/persistence/Cache.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/leaderboard/LeaderBoardViewModel.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/leaderboard/LeaderboardFragment.kt
  app/src/main/res/layout/fragment_leaderboard.xml
Labels: actual: 4h, Waiting for review

#94 Feat/play again and multi round mode
  app/src/androidTest/java/ch/epfl/sweng/rps/ComputerMatchTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/ui/friends/FriendsFragmentTest.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/GameFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/GameResultFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/HomeFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/MatchViewModel.kt
  app/src/main/res/drawable/ic_clock_pastel_col.xml
  app/src/main/res/layout/fragment_game.xml
  app/src/main/res/layout/fragment_game_result.xml
  app/src/main/res/layout/user_match_data.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: Waiting for review

#119 Safety check
  app/build.gradle
  app/src/main/java/ch/epfl/sweng/rps/LoadingActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Game.kt
  app/src/main/java/ch/epfl/sweng/rps/services/FirebaseGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/settings/SettingsActivity.kt
  firebase/functions/.eslintrc.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/src/index.ts
  firebase/functions/src/test_framework.ts
  package-lock.json
Labels: actual: 3h, Waiting for review

#116 Fix/refine stats page
  app/src/androidTest/java/ch/epfl/sweng/rps/StatisticsFragmentTest.kt
  app/src/main/java/ch/epfl/sweng/rps/db/FirebaseHelper.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Round.kt
  app/src/main/java/ch/epfl/sweng/rps/models/UserStat.kt
  app/src/main/java/ch/epfl/sweng/rps/services/OfflineTicTacToe.kt
  app/src/main/java/ch/epfl/sweng/rps/services/TicTacToeGame.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/statistics/MatchDetailsFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/statistics/StatisticsFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/statistics/StatisticsViewModel.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/statistics/StatsItemAdapter.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/tictactoe/TicTacToeChoiceFragment.kt
  app/src/main/res/drawable/loss.png
  app/src/main/res/drawable/tie.png
  app/src/main/res/drawable/win.png
  app/src/main/res/layout/fragment_leaderboard.xml
  app/src/main/res/layout/fragment_match_details.xml
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/layout/stats_card.xml
  app/src/main/res/layout/stats_scrolling.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/rps/services/TicTacToeGameTest.kt
Labels: Waiting for review, actual: 8h

#124 Feat/online game support
  app/src/main/java/ch/epfl/sweng/rps/models/AbstractUser.kt
  app/src/main/java/ch/epfl/sweng/rps/models/ComputerPlayer.kt
  app/src/main/java/ch/epfl/sweng/rps/models/RandomPlayer.kt
  app/src/main/java/ch/epfl/sweng/rps/models/User.kt
  app/src/main/java/ch/epfl/sweng/rps/services/FirebaseGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/GameService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/OfflineGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/GameFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/MatchViewModel.kt
Labels: Waiting for review

#120 Matchmaking screen
  app/src/androidTest/java/ch/epfl/sweng/rps/CacheTests.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/MatchmakingTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/services/FirebaseGameServiceTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/services/MatchmakingServiceTest.kt
  app/src/main/java/ch/epfl/sweng/rps/models/AbstractUser.kt
  app/src/main/java/ch/epfl/sweng/rps/models/ComputerPlayer.kt
  app/src/main/java/ch/epfl/sweng/rps/models/Game.kt
  app/src/main/java/ch/epfl/sweng/rps/models/GameMode.kt
  app/src/main/java/ch/epfl/sweng/rps/models/RandomPlayer.kt
  app/src/main/java/ch/epfl/sweng/rps/models/User.kt
  app/src/main/java/ch/epfl/sweng/rps/services/FirebaseGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/GameService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/MatchmakingService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/OfflineGameService.kt
  app/src/main/java/ch/epfl/sweng/rps/services/ServiceLocator.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/friends/FriendsFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/friends/InfoPageFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/GameFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/MatchmakingFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/MatchmakingViewModel.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/HomeFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/MatchViewModel.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/ChangeNotifier.kt
  app/src/main/java/ch/epfl/sweng/rps/utils/L.kt
  app/src/main/res/layout/fragment_matchmaking.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/rps/utils/ChangeNotifierTest.kt
  firebase/functions/src/index.ts
Labels: estimated: 6h, Waiting for review, actual: 6h

#72 Feat/ml pipeline
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/rps/vision/GraphicOverlayActivity.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/vision/GraphicOverlayTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/assets/model_1.tflite
  app/src/main/java/ch/epfl/sweng/rps/MainActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/camera/CameraFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/camera/CameraXLivePreviewActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/camera/CameraXViewModel.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/HomeFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/FrameMetadata.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/GraphicOverlay.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/InferenceInfoGraphic.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/LabelDetectorProcessor.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/LabelGraphic.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/ScopedExecutor.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/VisionImageProcessor.kt
  app/src/main/res/layout/activity_vision_camerax_live_preview.xml
  app/src/main/res/layout/graphic_overlay_test.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/test/java/ch/epfl/sweng/rps/vision/FrameMetadataTest.kt
  app/src/test/java/ch/epfl/sweng/rps/vision/ScopedExecutorTest.kt
  docs/ML_PIPELINE.md
Labels: Waiting for review

#144 Added docs for cache
  app/src/main/java/ch/epfl/sweng/rps/persistence/Cache.kt
Labels: Waiting for review

#145 TicTacToe fix and doc
  app/src/androidTest/java/ch/epfl/sweng/rps/TicTacToeTest.kt
  app/src/main/java/ch/epfl/sweng/rps/services/TicTacToeGame.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/tictactoe/TicTacToeFragment.kt
Labels: Waiting for review

#143 feat:display names during the match
  app/src/androidTest/java/ch/epfl/sweng/rps/GameButtonsTest.kt
  app/src/androidTest/java/ch/epfl/sweng/rps/ui/friends/FriendsFragmentTest.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/GameFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/MatchViewModel.kt
  app/src/main/res/layout/fragment_game.xml
  app/src/main/res/values/strings.xml
Labels: Waiting for review

#146 feat: Integrate the ML pipeline into the game
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/rps/ui/camera/CameraXLivePreviewActivity.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/camera/CameraXLivePreviewActivityContract.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/game/GameFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/ui/home/HomeFragment.kt
  app/src/main/java/ch/epfl/sweng/rps/vision/LabelDetectorProcessor.kt
  app/src/main/res/drawable/ic_baseline_camera_alt_48.xml
  app/src/main/res/layout/fragment_game.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: Waiting for review
